id: P009128
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:23.673854
source_metadata:
  id: bdr:W22346
  title: པདྨ་བཀའ་ཐང
  author: ''
  volumes:
    0d66b2f5680348cfa2c5c4ac01ca43bf:
      image_group_id: I1PD88203
      title: ''
      volume_number: 1
      total_pages: 590
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
